<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Everjobs Suite" duration-ms="179643" started-at="2020-05-26T18:41:12 IST" finished-at="2020-05-26T18:44:12 IST">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.qa.auto.modules.TestRunner@79be0360]" name="feature" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="SeleniumTest" duration-ms="179643" started-at="2020-05-26T18:41:12 IST" finished-at="2020-05-26T18:44:12 IST">
      <class name="com.qa.auto.modules.TestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.qa.auto.modules.TestRunner@79be0360]" name="setUpClass" is-config="true" duration-ms="365" started-at="2020-05-26T18:41:12 IST" finished-at="2020-05-26T18:41:13 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="feature(cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.qa.auto.modules.TestRunner@79be0360]" name="feature" duration-ms="179099" started-at="2020-05-26T18:41:13 IST" description="Runs Cucumber Feature" data-provider="features" finished-at="2020-05-26T18:44:12 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Proline Date Parser]]>
              </value>
            </param>
          </params>
          <exception class="cucumber.runtime.CucumberException">
            <message>
              <![CDATA[java.lang.AssertionError: expected [Sat Jan 01 2050 00:00:00 GMT+0000] but found [Sun Jan 01 1950 00:00:00 GMT+0000]]]>
            </message>
            <full-stacktrace>
              <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [Sat Jan 01 2050 00:00:00 GMT+0000] but found [Sun Jan 01 1950 00:00:00 GMT+0000]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at cucumber.api.testng.AbstractTestNGCucumberTests.feature(AbstractTestNGCucumberTests.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.AssertionError: expected [Sat Jan 01 2050 00:00:00 GMT+0000] but found [Sun Jan 01 1950 00:00:00 GMT+0000]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.qa.auto.stepdefination.HomePage.check_the_output_Invalid_Date_field(HomePage.java:31)
at âœ½.Then Check the output 'Sat Jan 01 2050 00:00:00 GMT+0000' field(HomePage.feature:22)
]]>
            </full-stacktrace>
          </exception> <!-- cucumber.runtime.CucumberException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- feature -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.qa.auto.modules.TestRunner@79be0360]" name="tearDownClass" is-config="true" duration-ms="10" started-at="2020-05-26T18:44:12 IST" finished-at="2020-05-26T18:44:12 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.qa.auto.modules.TestRunner -->
    </test> <!-- SeleniumTest -->
  </suite> <!-- Everjobs Suite -->
</testng-results>
